import openingsData from '../data/openings.json';
import type { Opening } from './types';

/** Map of position EPD -> opening label. Generated by scripts/build-openings.mjs. */
const OPENINGS = openingsData as Record<string, Opening>;

/** Reduce a full FEN to its position-identifying EPD (drops move clocks). */
export function fenToEpd(fen: string): string {
  return fen.split(' ').slice(0, 4).join(' ');
}

/** Look up the ECO opening for a position, if it is a named position. */
export function openingForEpd(epd: string): Opening | undefined {
  return OPENINGS[epd];
}

export function openingForFen(fen: string): Opening | undefined {
  return openingForEpd(fenToEpd(fen));
}

/**
 * Split a full opening name into its general -> specific segments.
 * Lichess names use ": " to separate the family from the variation and ", "
 * between sub-variations, e.g.
 *   "Sicilian Defense: Najdorf Variation, English Attack"
 *   -> ["Sicilian Defense", "Najdorf Variation", "English Attack"]
 */
export function nameSegments(name: string): string[] {
  const [family, rest] = splitFirst(name, ': ');
  if (rest === undefined) return [family];
  return [family, ...rest.split(', ')];
}

function splitFirst(s: string, sep: string): [string, string | undefined] {
  const i = s.indexOf(sep);
  if (i === -1) return [s, undefined];
  return [s.slice(0, i), s.slice(i + sep.length)];
}

/** The opening "family" (text before the first colon), e.g. "Sicilian Defense". */
export function openingFamily(name: string): string {
  return nameSegments(name)[0];
}
